# Generated by Django 4.1 on 2022-08-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('relacion', models.CharField(max_length=64)),
                ('nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
